# Generated by Django 2.1.2 on 2018-10-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=512, unique=True, verbose_name='Слово')),
                ('replacement', models.CharField(max_length=512, verbose_name='Русская Замена')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS pg_tgrm;'),
    ]
