# Generated by Django 2.2.4 on 2019-09-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stopword',
            options={'verbose_name': 'Слово', 'verbose_name_plural': 'Слова'},
        ),
    ]
