# Generated by Django 2.2.4 on 2019-08-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zritel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
