# Generated by Django 2.2.4 on 2019-09-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zritel', '0002_record_processed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Источник', 'verbose_name_plural': 'Источники'},
        ),
        migrations.AddField(
            model_name='source',
            name='alert_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
