# Generated by Django 2.2.4 on 2019-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zritel', '0004_source_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=models.CharField(help_text='Путь', max_length=512, unique=True),
        ),
    ]
